#!/bin/sh
export HOMEBREW_CASK_OPTS="--appdir=/Applications --caskroom=/etc/Caskroom"

brew "nvm"

gem install sass
gem install compass

npm install -g bower grunt-cli gulp-cli browserify forever webpack less yo